### PR TITLE
More updates and fixes

### PR DESCRIPTION
**Pull request by kosmiq**
This includes all updates up to Sage 8.5.0 about a month ago, all the fixes from @chuckn246 (plus refactored some of his code with proper attribute escapes, different PHP style, better alignment with WordPress-Core code style plus made more strings translatable, adds namespaces).

So it works with newer versions of node, incorporates composer and more.

Many thanks to @chuckn246 for the hard word on the features. Sorry I didn't pulled your changes correctly into my fork instead of this..

Commented out flex-grid since Zurb recommends using only one at a time.

### CODE REVIEW

**Comment by christianmagill** [comment]
Thanks for your work on this! When including the individual js files as you have, shouldn't Babel be used to transpile during the Gulp task?

https://foundation.zurb.com/sites/docs/javascript.html#babel-required

**Comment by kosmiq** [comment]
You might be right. I only tested in modern browsers and meant to revisit it sooner than I have. If you have the time, please try and report back. Otherwise I'll keep it in mind when I get around to update it to foundation 6.3 that was released a few days ago.

**Comment by christianmagill** [comment]
Cool. If I get a few to work on it I'll post back here. Please do the same. 

Also it looks like foundation.core.js and foundation.util.mediaQuery.js should be loaded first.

https://foundation.zurb.com/sites/docs/javascript.html#file-structure

**Comment by kosmiq** [comment]
I'll make sure to mirror the JS inclusion order used in 6.3 when I get to it. Thanks for noticing it!

**Comment by kosmiq** [comment]
@christianmagill it just hit me: do we need babel translation if we include plugins from /dist folder? I'm not sure what's required since we do not really build from source. I'll have to do some digging.

**Comment by christianmagill** [comment]
I'm not sure. Would be nice to have es6 available though.

**Comment by kosmiq** [comment]
So I took a look, and files within foundation-sites/dist/js does not require babel. If we however use files from foundation-sites/js we would absolutely need it.

But I agree that we should have babel there anyway, so it's easy to use ES6 whenever.

**Comment by christianmagill** [comment]
Good to know.

**Comment by kosmiq** [comment]
Since [Beta 2 of Sage 9](https://github.com/roots/sage/pull/1813) adds the option to select Foundation as framework I will be abandoning this. I can't justify investing the time since an official solution has arrived (altough in beta).

**Comment by christianmagill** [comment]
Sounds good. I was excited to see the option appear. Now I'm just hoping blade becomes an option as well.

**Comment by kosmiq** [comment]
Blade is actually there since beta 1. Some issues with woocommerce but they're working on it.

https://github.com/roots/sage/releases/tag/9.0.0-beta.1
https://github.com/roots/sage/pull/1765
https://github.com/roots/sage/pull/1777

I'm reluctant to use beta versions for serious projects but really looking forward to the first real release. Whenever that happens.

**Pull request closed without merging**
